from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.setEnabled(True)
        # window.resize(592, 439)
        window.setFixedSize(592, 439)
        self.central_widget = QtWidgets.QWidget(window)
        self.central_widget.setEnabled(True)
        self.central_widget.setObjectName("central_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.card_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.card_1.setMaximumSize(QtCore.QSize(80, 120))
        self.card_1.setText("")
        self.card_1.setScaledContents(True)
        self.card_1.setAlignment(QtCore.Qt.AlignCenter)
        self.card_1.setObjectName("card_1")
        self.gridLayout.addWidget(self.card_1, 0, 1, 1, 1)
        self.card_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.card_4.setMaximumSize(QtCore.QSize(80, 120))
        self.card_4.setText("")
        self.card_4.setScaledContents(True)
        self.card_4.setAlignment(QtCore.Qt.AlignCenter)
        self.card_4.setObjectName("card_4")
        self.gridLayout.addWidget(self.card_4, 1, 1, 1, 1)
        self.card_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.card_3.setMaximumSize(QtCore.QSize(80, 120))
        self.card_3.setText("")
        self.card_3.setScaledContents(True)
        self.card_3.setAlignment(QtCore.Qt.AlignCenter)
        self.card_3.setObjectName("card_3")
        self.gridLayout.addWidget(self.card_3, 1, 0, 1, 1)
        self.card_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.card_2.setMaximumSize(QtCore.QSize(80, 120))
        self.card_2.setText("")
        self.card_2.setScaledContents(True)
        self.card_2.setAlignment(QtCore.Qt.AlignCenter)
        self.card_2.setObjectName("card_2")
        self.gridLayout.addWidget(self.card_2, 0, 2, 1, 1)
        self.card_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.card_0.setMaximumSize(QtCore.QSize(80, 120))
        self.card_0.setText("")
        self.card_0.setScaledContents(True)
        self.card_0.setAlignment(QtCore.Qt.AlignCenter)
        self.card_0.setObjectName("card_0")
        self.gridLayout.addWidget(self.card_0, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.central_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(310, 10, 271, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.card_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.card_5.setMaximumSize(QtCore.QSize(80, 120))
        self.card_5.setText("")
        self.card_5.setScaledContents(True)
        self.card_5.setAlignment(QtCore.Qt.AlignCenter)
        self.card_5.setObjectName("card_5")
        self.gridLayout_2.addWidget(self.card_5, 0, 0, 1, 1)
        self.card_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.card_8.setMaximumSize(QtCore.QSize(80, 120))
        self.card_8.setText("")
        self.card_8.setScaledContents(True)
        self.card_8.setAlignment(QtCore.Qt.AlignCenter)
        self.card_8.setObjectName("card_8")
        self.gridLayout_2.addWidget(self.card_8, 1, 0, 1, 1)
        self.card_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.card_7.setMaximumSize(QtCore.QSize(80, 120))
        self.card_7.setText("")
        self.card_7.setScaledContents(True)
        self.card_7.setAlignment(QtCore.Qt.AlignCenter)
        self.card_7.setObjectName("card_7")
        self.gridLayout_2.addWidget(self.card_7, 0, 2, 1, 1)
        self.card_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.card_6.setMaximumSize(QtCore.QSize(80, 120))
        self.card_6.setText("")
        self.card_6.setScaledContents(True)
        self.card_6.setAlignment(QtCore.Qt.AlignCenter)
        self.card_6.setObjectName("card_6")
        self.gridLayout_2.addWidget(self.card_6, 0, 1, 1, 1)
        self.card_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.card_9.setMaximumSize(QtCore.QSize(80, 120))
        self.card_9.setText("")
        self.card_9.setScaledContents(True)
        self.card_9.setAlignment(QtCore.Qt.AlignCenter)
        self.card_9.setObjectName("card_9")
        self.gridLayout_2.addWidget(self.card_9, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 571, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        font = QtGui.QFont()
        font.setPointSize(22)
        self.player_score_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.player_score_label.setFont(font)
        self.player_score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.player_score_label.setObjectName("player_score_label")
        self.horizontalLayout_3.addWidget(self.player_score_label)
        self.ai_score_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ai_score_label.setFont(font)
        self.ai_score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ai_score_label.setObjectName("ai_score_label")
        self.horizontalLayout_3.addWidget(self.ai_score_label)
        self.reset_button = QtWidgets.QPushButton(self.central_widget)
        self.reset_button.setGeometry(QtCore.QRect(210, 340, 168, 38))
        self.reset_button.setObjectName("reset_button")
        self.widget = QtWidgets.QWidget(self.central_widget)
        self.widget.setGeometry(QtCore.QRect(10, 390, 571, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.draw_button = QtWidgets.QPushButton(self.widget)
        self.draw_button.setObjectName("draw_button")
        self.horizontalLayout.addWidget(self.draw_button)
        self.stick_button = QtWidgets.QPushButton(self.widget)
        self.stick_button.setObjectName("stick_button")
        self.horizontalLayout.addWidget(self.stick_button)
        window.setCentralWidget(self.central_widget)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Blackjack"))
        self.draw_button.setText(_translate("window", "Draw a card"))
        self.stick_button.setText(_translate("window", "Stick"))
        self.stick_button.setEnabled(False)
        self.reset_button.setText(_translate("window", "Play again"))
        self.reset_button.setVisible(False)
        for x in range(10):
            eval(f"self.card_{x}").setVisible(False)
            self.addShadowEffect(eval(f"self.card_{x}"))

    def addShadowEffect(self, item):
        effect = QtWidgets.QGraphicsDropShadowEffect()
        effect.setBlurRadius(1)
        effect.setColor(QtGui.QColor("black"))
        effect.setOffset(1,1)
        item.setGraphicsEffect(effect)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
